#ifndef VERSION_H 
#define	VERSION_H 
 
#define VERSION "18:01 11.03.2023" 
 
#define VERSION_MINUTE_BCD 0x01 
#define VERSION_HOUR_BCD 0x18 
#define VERSION_DAY_OF_WEEK_BCD 0x07 
#define VERSION_DAY_OF_MONTH_BCD 0x11 
#define VERSION_MONTH_BCD 0x03 
#define VERSION_YEAR_BCD 0x23 
#define VERSION_YEAR 23 
 
#endif	/* VERSION_H */ 
