#ifndef VERSION_H 
#define	VERSION_H 
 
#define VERSION_STRING "22:14 07.08.2021"; 
 
#define VERSION_MINUTE_BCD 0x14 
#define VERSION_HOUR_BCD 0x22 
#define VERSION_DAY_OF_WEEK_BCD 0x06 
#define VERSION_DAY_OF_MONTH_BCD 0x07 
#define VERSION_MONTH_BCD 0x08 
#define VERSION_YEAR_BCD 0x21 
 
#endif	/* VERSION_H */ 
